### PR TITLE
Updated Part-4 to use PyQt5

### PR DESCRIPTION
**Pull request by Jock2**
I found your tutorial very helpfull, thanks.
I followed it using PyQt5, and have now added the required changes to your code.

### CODE REVIEW

**Comment by goldsborough** [comment]
Hi, thanks for the pull request. The code itself looks good, however the problem is that the tutorial parts build on each other, meaning that if one part uses PyQt5, all parts should (for consistency; it shouldn't be that one part builds properly for someone while another doesn't). Do you think you could integrate (i.e. copy) your changes into the other parts so that all parts use PyQt5?

**Comment by Jock2** [comment]
There's now a PyQt5 version for all 4 parts. I also added a summery of the changes.

**Comment by goldsborough** [comment]
I just cloned your fork and installed PyQt5 and everything builds well. However, there seems to be an encoding issue which needs to be resolved. Can you please paste the line `# -*- coding: utf-8 -*-` to the top of part-1.py, part-2.py, part-3.py and part-4.py? I'll merge right after.

**Comment by Jock2** [comment]
Strange. I have my editor set to utf-8.

**Comment by goldsborough** [comment]
@Jock2 Thanks :blush:

**Pull request merged**
